### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman100**

### CODE REVIEW

**Comment by Justman100** [comment]
@stropho

**Comment by stropho** [comment]
Thanks for pointing out the needed updates. I've been postponing it for a while. Few points:
- removing package-lock is not an option
- updating dependencies requiring newer nodejs version that this project currently does without changing this information in package.json - not an option 😉 

Before digging more into this, tell me, what is the **reason number 1 for you** that requires this update?

**Comment by Justman100** [comment]
> removing package-lock is not an option

Why? Nobody needs

> updating dependencies requiring newer nodejs version that this project currently does without changing this information in package.json - not an option 😉

They probably don't need whole new generations of NodeJS

**Comment by stropho** [comment]
> > removing package-lock is not an option
> 
> Why? Nobody needs
> 
Maybe you don't need it, but others do. As you can see, the Node.js CI pipeline fails, because it is unable to install node_modules using `npm ci` command


___

 Once again, why do you need the updates? As far as I know, there is only a single dependency `magic-string`, marked as external, that you could override with newer version yourself in the project where you use it. Everything else is devDependency, and it should not concern you as long as you are "only a user" of this project/package.

**Comment by Justman100** [comment]
> > > removing package-lock is not an option
> > 
> > 
> > Why? Nobody needs
> 
> Once again, why do you need the updates? As far as I know, there is only a single dependency `magic-string`, marked as external, that you could override with newer version yourself in the project where you use it. Everything else is devDependency, and it should not concern you as long as you are "only a user" of this project/package.

Because one simply updates packages? Because of security vulnerabilities? New functions?

**Comment by Justman100** [comment]
Or do you only update your Windows every 6 years?

**Comment by stropho** [comment]
>  Because of security vulnerabilities? New functions?

Pls give me a specific example what is affecting you.

It will help me to know once I get to the updating...

Your PR is failing, and will not be merge in that condition

**Comment by Justman100** [comment]
> > Because of security vulnerabilities? New functions?
> 
> Pls give me a specific example what is affecting you.
> 
> It will help me to know once I get to the updating...
> 
> Your PR is failing, and will not be merge in that condition

First cry, why update, and then do it yourself? Let's get it right first! And without me! Because I'm gone! Handle this shit yourself

**Comment by stropho** [comment]
@Justman100 nobody was crying. I just wanted to know what specific problem it solves for you. But it looks like you don't know, or wasn't able to say.

Anyway, thanks again for reminding that there are updates that should be handled 😃

**Comment by Justman100** [comment]
> Anyway, thanks again for reminding that there are updates that should be handled 😃

Yes, thank you for wasting my time! Some people are really sad...

**Pull request closed without merging**
